spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8080

#JWT Configuration
jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 86400000
  refresh-expiration: 604800000

logging:
  level:
    com.example.myownessay: INFO
    org.springframework.security: INFO